import { seoBlogPosts } from './seo-blog-posts.js';

const dateFromNow = (days) => {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date;
};

export const brands = [
  { id: 'brand_shopee', name: 'Shopee', slug: 'shopee', platform: 'shopee', description: 'Sàn thương mại điện tử phổ biến với nhiều mã giảm giá, freeship và flash sale hằng ngày.', website_url: 'https://shopee.vn', is_featured: true, is_active: true, voucher_count: 15, click_count: 0, sort_order: 1 },
  { id: 'brand_lazada', name: 'Lazada', slug: 'lazada', platform: 'lazada', description: 'Nhiều deal điện tử, thời trang và voucher ngành hàng được cập nhật thường xuyên.', website_url: 'https://www.lazada.vn', is_featured: true, is_active: true, voucher_count: 10, click_count: 0, sort_order: 2 },
  { id: 'brand_tiki', name: 'Tiki', slug: 'tiki', platform: 'tiki', description: 'Ưu đãi sách, gia dụng, điện tử và giao nhanh cho khách hàng Việt Nam.', website_url: 'https://tiki.vn', is_featured: true, is_active: true, voucher_count: 8, click_count: 0, sort_order: 3 },
  { id: 'brand_tiktok_shop', name: 'TikTok Shop', slug: 'tiktok-shop', platform: 'tiktok_shop', description: 'Deal live, voucher shop và mã giảm giá theo chiến dịch TikTok Shop.', website_url: 'https://www.tiktok.com', is_featured: true, is_active: true, voucher_count: 6, click_count: 0, sort_order: 4 },
  { id: 'brand_samsung', name: 'Samsung', slug: 'samsung', platform: 'other', description: 'Ưu đãi điện thoại, thiết bị gia dụng và phụ kiện Samsung.', website_url: 'https://www.samsung.com/vn', is_featured: true, is_active: true, voucher_count: 4, click_count: 0, sort_order: 5 },
  { id: 'brand_nike', name: 'Nike', slug: 'nike', platform: 'other', description: 'Deal giày, quần áo thể thao và phụ kiện Nike.', website_url: 'https://www.nike.com/vn', is_featured: true, is_active: true, voucher_count: 3, click_count: 0, sort_order: 6 },
  { id: 'brand_unilever', name: 'Unilever', slug: 'unilever', platform: 'other', description: 'Voucher sản phẩm chăm sóc cá nhân và gia đình.', website_url: 'https://www.unilever.com.vn', is_featured: true, is_active: true, voucher_count: 5, click_count: 0, sort_order: 7 },
  { id: 'brand_loreal', name: "L'Oréal", slug: 'loreal', platform: 'lazada', description: 'Ưu đãi mỹ phẩm, skincare và quà tặng từ L’Oréal.', website_url: 'https://www.lorealparis.com.vn', is_featured: true, is_active: true, voucher_count: 4, click_count: 0, sort_order: 8 },
  { id: 'brand_grab', name: 'Grab', slug: 'grab', platform: 'other', description: 'Mã giảm giá đồ ăn, di chuyển và dịch vụ Grab.', website_url: 'https://www.grab.com/vn', is_featured: true, is_active: true, voucher_count: 3, click_count: 0, sort_order: 9 },
  { id: 'brand_the_coffee_house', name: 'The Coffee House', slug: 'the-coffee-house', platform: 'other', description: 'Deal đồ uống và voucher thành viên.', website_url: 'https://thecoffeehouse.com', is_featured: true, is_active: true, voucher_count: 2, click_count: 0, sort_order: 10 },
];

export const categories = [
  { id: 'cat_thoi_trang', name: 'Thời Trang', slug: 'thoi-trang', icon: 'Shirt', description: 'Quần áo, phụ kiện, giày dép', is_active: true, voucher_count: 12, sort_order: 1 },
  { id: 'cat_my_pham', name: 'Mỹ Phẩm', slug: 'my-pham', icon: 'Sparkles', description: 'Mỹ phẩm, chăm sóc da, nước hoa', is_active: true, voucher_count: 8, sort_order: 2 },
  { id: 'cat_me_va_be', name: 'Mẹ & Bé', slug: 'me-va-be', icon: 'Baby', description: 'Sữa, tã, đồ chơi và đồ dùng cho bé', is_active: true, voucher_count: 6, sort_order: 3 },
  { id: 'cat_dien_tu', name: 'Điện Tử', slug: 'dien-tu', icon: 'Smartphone', description: 'Điện thoại, laptop, phụ kiện', is_active: true, voucher_count: 10, sort_order: 4 },
  { id: 'cat_nha_cua', name: 'Nhà Cửa', slug: 'nha-cua', icon: 'Home', description: 'Gia dụng, nội thất, đồ bếp', is_active: true, voucher_count: 5, sort_order: 5 },
  { id: 'cat_suc_khoe', name: 'Sức Khỏe', slug: 'suc-khoe', icon: 'Heart', description: 'Sản phẩm chăm sóc sức khỏe và đông y', is_active: true, voucher_count: 4, sort_order: 6 },
  { id: 'cat_du_lich', name: 'Du Lịch', slug: 'du-lich', icon: 'Plane', description: 'Khách sạn, vé máy bay, trải nghiệm', is_active: true, voucher_count: 3, sort_order: 7 },
  { id: 'cat_do_an', name: 'Đồ Ăn', slug: 'do-an', icon: 'UtensilsCrossed', description: 'Nhà hàng, đồ uống, giao đồ ăn', is_active: true, voucher_count: 7, sort_order: 8 },
];

export const vouchers = [
  {
    id: 'voucher_grab_food_giam_30',
    title: 'Grab Food - Giảm 30% đơn đồ ăn',
    slug: 'grab-food-giam-30',
    code: 'GRABFOOD30',
    description: 'Giảm 30% cho đơn GrabFood từ 80K',
    terms: 'Áp dụng cho đơn GrabFood đủ điều kiện.',
    discount_type: 'percent',
    discount_value: '30%',
    min_order_value: '80.000đ',
    max_discount: '50.000đ',
    end_date: dateFromNow(12),
    status: 'active',
    voucher_type: 'coupon',
    platform: 'other',
    brand_id: 'brand_grab',
    brand_name: 'Grab',
    category_id: 'cat_do_an',
    category_name: 'Đồ Ăn',
    original_url: 'https://www.grab.com/vn/food/',
    tracking_url: 'https://www.grab.com/vn/food/',
    is_hot: true,
    is_verified: true,
    sort_order: 100,
    created_date: dateFromNow(-20),
  },
  {
    id: 'voucher_shopee_giam_200k_dien_tu',
    title: 'Shopee - Giảm 200K cho đồ điện tử',
    slug: 'shopee-giam-200k-dien-tu',
    code: 'SPDT200K',
    description: 'Áp dụng cho laptop, điện thoại, phụ kiện tại Shopee Mall',
    discount_type: 'fixed',
    discount_value: '200.000đ',
    min_order_value: '2.000.000đ',
    end_date: dateFromNow(16),
    status: 'active',
    voucher_type: 'coupon',
    platform: 'shopee',
    brand_id: 'brand_shopee',
    brand_name: 'Shopee',
    category_id: 'cat_dien_tu',
    category_name: 'Điện Tử',
    original_url: 'https://shopee.vn',
    tracking_url: 'https://shopee.vn',
    is_hot: true,
    is_verified: true,
    sort_order: 90,
    created_date: dateFromNow(-19),
  },
  {
    id: 'voucher_tiktok_shop_flash_sale_1d',
    title: 'TikTok Shop - Flash Sale 1đ mỗi ngày',
    slug: 'tiktok-shop-flash-sale-1d',
    description: 'Sản phẩm chỉ 1đ mỗi ngày lúc 12h trưa và 20h tối',
    discount_type: 'percent',
    discount_value: '99%',
    end_date: dateFromNow(8),
    status: 'active',
    voucher_type: 'flash_sale',
    platform: 'tiktok_shop',
    brand_id: 'brand_tiktok_shop',
    brand_name: 'TikTok Shop',
    category_id: 'cat_thoi_trang',
    category_name: 'Thời Trang',
    original_url: 'https://www.tiktok.com',
    tracking_url: 'https://www.tiktok.com',
    is_hot: true,
    sort_order: 80,
    created_date: dateFromNow(-18),
  },
  {
    id: 'voucher_tiki_freeship_tikinow',
    title: 'Tiki - Freeship không giới hạn TikiNOW',
    slug: 'tiki-freeship-tikinow',
    code: 'TIKIFREE',
    description: 'Miễn phí giao hàng cho đơn TikiNOW',
    discount_type: 'freeship',
    discount_value: 'Miễn phí vận chuyển',
    min_order_value: '149.000đ',
    end_date: dateFromNow(18),
    status: 'active',
    voucher_type: 'freeship',
    platform: 'tiki',
    brand_id: 'brand_tiki',
    brand_name: 'Tiki',
    category_id: 'cat_nha_cua',
    category_name: 'Nhà Cửa',
    original_url: 'https://tiki.vn',
    tracking_url: 'https://tiki.vn',
    is_hot: true,
    is_verified: true,
    sort_order: 70,
    created_date: dateFromNow(-17),
  },
  {
    id: 'voucher_loreal_tang_qua_500k',
    title: "L'Oréal - Tặng quà khi mua từ 500K trên Lazada",
    slug: 'loreal-tang-qua-500k',
    description: 'Nhận set quà skincare trị giá 300K khi mua đơn từ 500K',
    discount_type: 'gift',
    discount_value: 'Tặng quà 300K',
    min_order_value: '500.000đ',
    end_date: dateFromNow(22),
    status: 'active',
    voucher_type: 'deal',
    platform: 'lazada',
    brand_id: 'brand_loreal',
    brand_name: "L'Oréal",
    category_id: 'cat_my_pham',
    category_name: 'Mỹ Phẩm',
    original_url: 'https://www.lazada.vn',
    tracking_url: 'https://www.lazada.vn',
    is_hot: true,
    sort_order: 60,
    created_date: dateFromNow(-16),
  },
  {
    id: 'voucher_nike_sale_40_giay_running',
    title: 'Nike - Sale 40% toàn bộ giày Running',
    slug: 'nike-sale-40-giay-running',
    description: 'Giảm giá 40% cho tất cả giày Nike Running tại store',
    discount_type: 'percent',
    discount_value: '40%',
    end_date: dateFromNow(25),
    status: 'active',
    voucher_type: 'deal',
    platform: 'other',
    brand_id: 'brand_nike',
    brand_name: 'Nike',
    category_id: 'cat_thoi_trang',
    category_name: 'Thời Trang',
    original_url: 'https://www.nike.com/vn',
    tracking_url: 'https://www.nike.com/vn',
    is_hot: true,
    sort_order: 50,
    created_date: dateFromNow(-15),
  },
  {
    id: 'voucher_thong_cat_33_all',
    title: '[Đông Y Thông Cát CN HCM]-Giảm 33,000 VNĐ cho đơn tối thiểu 200,000 VNĐ',
    slug: '-ng-y-th-ng-c-t-cn-hcm-gi-m-33-000-vn-cho-n-t-i-thi-u-200-000-vn-',
    code: 'THONG33ALL',
    description: '[Đông Y Thông Cát CN HCM] [Đông Y Thông Cát CN HCM]-Giảm 33,000 VNĐ cho đơn tối thiểu 200,000 VNĐ',
    end_date: dateFromNow(-1),
    status: 'active',
    voucher_type: 'coupon',
    platform: 'shopee',
    brand_id: 'brand_shopee',
    brand_name: 'shopee',
    category_id: 'cat_suc_khoe',
    category_name: 'Sức Khỏe',
    original_url: 'https://shopee.vn',
    tracking_url: 'https://shopee.vn',
    sort_order: 10,
    created_date: dateFromNow(0),
  },
  {
    id: 'voucher_thong_cat_33_219',
    title: '[Đông Y Thông Cát CN HCM]-Giảm 33,000 VNĐ cho đơn tối thiểu 219,000 VNĐ',
    slug: '-ng-y-th-ng-c-t-cn-hcm-gi-m-33-000-vn-cho-n-t-i-thi-u-219-000-vn-',
    code: 'THONG6K33',
    description: '[Đông Y Thông Cát CN HCM] [Đông Y Thông Cát CN HCM]-Giảm 33,000 VNĐ cho đơn tối thiểu 219,000 VNĐ',
    end_date: dateFromNow(-1),
    status: 'active',
    voucher_type: 'coupon',
    platform: 'shopee',
    brand_id: 'brand_shopee',
    brand_name: 'shopee',
    category_id: 'cat_suc_khoe',
    category_name: 'Sức Khỏe',
    original_url: 'https://shopee.vn',
    tracking_url: 'https://shopee.vn',
    sort_order: 9,
    created_date: dateFromNow(-1),
  },
  {
    id: 'voucher_thong_cat_45_299',
    title: '[Đông Y Thông Cát CN HCM]-Giảm 45,000 VNĐ cho đơn tối thiểu 299,000 VNĐ',
    slug: '-ng-y-th-ng-c-t-cn-hcm-gi-m-45-000-vn-cho-n-t-i-thi-u-299-000-vn-',
    code: 'THONG6K45',
    description: '[Đông Y Thông Cát CN HCM] [Đông Y Thông Cát CN HCM]-Giảm 45,000 VNĐ cho đơn tối thiểu 299,000 VNĐ',
    end_date: dateFromNow(-1),
    status: 'active',
    voucher_type: 'coupon',
    platform: 'shopee',
    brand_id: 'brand_shopee',
    brand_name: 'shopee',
    category_id: 'cat_suc_khoe',
    category_name: 'Sức Khỏe',
    original_url: 'https://shopee.vn',
    tracking_url: 'https://shopee.vn',
    sort_order: 8,
    created_date: dateFromNow(-2),
  },
  {
    id: 'voucher_thong_cat_66_399',
    title: '[Đông Y Thông Cát CN HCM]-Giảm 66,000 VNĐ cho đơn tối thiểu 399,000 VNĐ',
    slug: '-ng-y-th-ng-c-t-cn-hcm-gi-m-66-000-vn-cho-n-t-i-thi-u-399-000-vn-',
    code: 'THONG6K66',
    description: '[Đông Y Thông Cát CN HCM] [Đông Y Thông Cát CN HCM]-Giảm 66,000 VNĐ cho đơn tối thiểu 399,000 VNĐ',
    end_date: dateFromNow(-1),
    status: 'active',
    voucher_type: 'coupon',
    platform: 'shopee',
    brand_id: 'brand_shopee',
    brand_name: 'shopee',
    category_id: 'cat_suc_khoe',
    category_name: 'Sức Khỏe',
    original_url: 'https://shopee.vn',
    tracking_url: 'https://shopee.vn',
    sort_order: 7,
    created_date: dateFromNow(-3),
  },
  {
    id: 'voucher_ember_brown_6k',
    title: '[Ember Brown]-Giảm 6,000 VNĐ cho đơn tối thiểu 139,000 VNĐ',
    slug: '-ember-brown-gi-m-6-000-vn-cho-n-t-i-thi-u-139-000-vn-',
    code: 'EMBER6K',
    description: '[Ember Brown] [Ember Brown]-Giảm 6,000 VNĐ cho đơn tối thiểu 139,000 VNĐ',
    end_date: dateFromNow(7),
    status: 'active',
    voucher_type: 'coupon',
    platform: 'shopee',
    brand_id: 'brand_shopee',
    brand_name: 'shopee',
    category_id: 'cat_thoi_trang',
    category_name: 'Thời Trang',
    original_url: 'https://shopee.vn',
    tracking_url: 'https://shopee.vn',
    sort_order: 6,
    created_date: dateFromNow(-4),
  },
  {
    id: 'voucher_bikinisaobien_5',
    title: '[BikiniSaoBienHCM]-Giảm 5%-tối đa 10,000 VNĐ cho đơn tối thiểu 199,000 VNĐ',
    slug: '-bikinisaobienhcm-gi-m-5-t-i-a-10-000-vn-cho-n-t-i-thi-u-199-000-vn-',
    code: 'BIKII2PMPL',
    description: '[BikiniSaoBienHCM] [BikiniSaoBienHCM]-Giảm 5%-tối đa 10,000 VNĐ cho đơn tối thiểu 199,000 VNĐ',
    end_date: dateFromNow(10),
    status: 'active',
    voucher_type: 'coupon',
    platform: 'shopee',
    brand_id: 'brand_shopee',
    brand_name: 'shopee',
    category_id: 'cat_thoi_trang',
    category_name: 'Thời Trang',
    original_url: 'https://shopee.vn',
    tracking_url: 'https://shopee.vn',
    sort_order: 5,
    created_date: dateFromNow(-5),
  },
];

export const blogPosts = seoBlogPosts.map((post, index) => ({
  ...post,
  sort_order: index + 1,
}));

export const staleSeedBlogPostIds = [
  'blog-cach-dung-ma-giam-gia',
  'blog-san-sale-shopee-lazada',
];

export const staleSeedVoucherIds = [
  'voucher_shopee_hot_50',
  'voucher_shopee_freeship',
  'voucher_lazada_flash_sale',
  'voucher_tiki_book',
  'voucher_tiktok_shop_live',
  'voucher_lazada_home',
  'voucher_shopee_me_be',
  'voucher_tiki_electronics',
];

export const staleSeedCategoryIds = [
  'cat_lam_dep',
  'cat_sach',
  'cat_an_uong',
];
